#
# application.yml — главный конфигурационный файл Spring Boot.

# Что нужно сделать:
#   - Указать порт приложения.
#   - Указать настройки подключения к базе данных.
#   - Настроить параметры безопасности и JWT.
#   - Включить Swagger UI.


spring:
  application:
    name: bankrest
  
  datasource:
    url: jdbc:postgresql://localhost:5432/bankrest
    username: bankrest
    password: bankrest

server:
  port: 8080

application:
  security:
    jwt:
      secret-key: 4bb6d1dfbafb64a681139d1586b6f1160d18159afd57c8c79136d7490630407c
      access-token-expiration: 86400000
      refresh-token-expiration: 604800000


